export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOADER = 'AUTH_LOADER';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const GET_USER_NAME = 'GET_USER_NAME';
export const GET_USER_THEME = 'GET_USER_THEME';

export const SET_POSTS_IN_STATE = 'SET_POSTS_IN_STATE';
export const POST_LOADING_FALSE = 'POST_LOADING_FALSE';
export const POST_LOADING_TRUE = 'POST_LOADING_TRUE';
export const GET_LOADING_FALSE = 'GET_LOADING_FALSE';
export const GET_LOADING_TRUE = 'GET_LOADING_TRUE';

export const SET_COMMENTS_IN_STATE = 'SET_COMMENTS_POSTS_IN_STATE';
export const SET_ALL_COMMENTS_IN_STATE = 'SET_ALL_COMMENTS_POSTS_IN_STATE';
export const POST_COMMENTS_LOADING_FALSE = 'POST_COMMENTS_LOADING_FALSE';
export const POST_COMMENTS_LOADING_TRUE = 'POST_COMMENTS_LOADING_TRUE';
export const GET_COMMENTS_LOADING_FALSE = 'GET_COMMENTS_LOADING_FALSE';
export const GET_COMMENTS_LOADING_TRUE = 'GET_COMMENTS_LOADING_TRUE';

export const LIKE_LOADING_TRUE = 'LIKE_LOADING_TRUE';
export const LIKE_LOADING_FALSE = 'LIKE_LOADING_FALSE';

export const LIKE_BUTTON_TIMEOUT_TRUE = 'LIKE_BUTTON_TIMEOUT_TRUE';
export const LIKE_BUTTON_TIMEOUT_FALSE = 'LIKE_BUTTON_TIMEOUT_FALSE';

export const SET_SEARCH_MODAL_TRUE = 'SET_SEARCH_MODAL_TRUE';
export const SET_SEARCH_MODAL_FALSE = 'SET_SEARCH_MODAL_FALSE';
export const SET_SEARCH_CONTENT = 'SET_SEARCH_CONTENT';
export const SET_SEARCHED_USERS = 'SET_SEARCHED_USERS';
export const SET_SEARCHED_POSTS = 'SET_SEARCHED_POSTS';